// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package psql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Source struct {
	SourceID      int32
	Name          string
	LastFetchedAt pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type SourcesItem struct {
	SourceItemID int32
	SourceID     pgtype.Int4
	Url          pgtype.Text
	Title        pgtype.Text
	TextContent  pgtype.Text
	Excerpt      pgtype.Text
	Language     pgtype.Text
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamp
}
