// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package psql

import (
	"context"
)

const createReaction = `-- name: CreateReaction :exec
INSERT INTO reactions (source_item_id, type, created_at) VALUES (
    $1, $2, CURRENT_TIMESTAMP
)
`

type CreateReactionParams struct {
	SourceItemID int32
	Type         ReactionsType
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) error {
	_, err := q.db.Exec(ctx, createReaction, arg.SourceItemID, arg.Type)
	return err
}
