// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources_items.sql

package psql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceItem = `-- name: CreateSourceItem :one
INSERT INTO sources_items (source_id, url, title, text_content, excerpt, language, published_at, created_at) VALUES($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP) RETURNING source_item_id
`

type CreateSourceItemParams struct {
	SourceID    pgtype.Int4
	Url         pgtype.Text
	Title       pgtype.Text
	TextContent pgtype.Text
	Excerpt     pgtype.Text
	Language    pgtype.Text
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) CreateSourceItem(ctx context.Context, arg CreateSourceItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSourceItem,
		arg.SourceID,
		arg.Url,
		arg.Title,
		arg.TextContent,
		arg.Excerpt,
		arg.Language,
		arg.PublishedAt,
	)
	var source_item_id int32
	err := row.Scan(&source_item_id)
	return source_item_id, err
}
