// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package psql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (name, created_at, updated_at)
VALUES ( $1, $2, CURRENT_TIMESTAMP )
RETURNING source_id
`

type CreateSourceParams struct {
	Name      string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSource, arg.Name, arg.CreatedAt)
	var source_id int32
	err := row.Scan(&source_id)
	return source_id, err
}

const getSourceIdByName = `-- name: GetSourceIdByName :one
SELECT source_id FROM sources WHERE name = $1
`

func (q *Queries) GetSourceIdByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getSourceIdByName, name)
	var source_id int32
	err := row.Scan(&source_id)
	return source_id, err
}

const getSourceLastFetchedAtByName = `-- name: GetSourceLastFetchedAtByName :one
SELECT last_fetched_at FROM sources WHERE name = $1
`

func (q *Queries) GetSourceLastFetchedAtByName(ctx context.Context, name string) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getSourceLastFetchedAtByName, name)
	var last_fetched_at pgtype.Timestamp
	err := row.Scan(&last_fetched_at)
	return last_fetched_at, err
}

const setSourceLastFetchedAtByName = `-- name: SetSourceLastFetchedAtByName :exec
UPDATE SOURCES
  SET last_fetched_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE name = $1
`

type SetSourceLastFetchedAtByNameParams struct {
	Name          string
	LastFetchedAt pgtype.Timestamp
}

func (q *Queries) SetSourceLastFetchedAtByName(ctx context.Context, arg SetSourceLastFetchedAtByNameParams) error {
	_, err := q.db.Exec(ctx, setSourceLastFetchedAtByName, arg.Name, arg.LastFetchedAt)
	return err
}
